---
title: "MB5370-Marine data analysis- Coral Bleaching"
output: html_document
date: "2026-06-28"
---

## Introduction
This project will be about the bleaching severity along different coral species throughout regions of the world. In hoping to assess how parts of the world have different bleaching severity observation. It would be interesting to observe differences and/or similarities in how affected coral bleaching changes per year and within each region. 


```{r}
# Read the csv file of the coral bleaching dataset
coral_bleaching<-read.csv("C:/Users/jd131798/Downloads/Marine_data_analysis/Data/Coral_Bleaching.csv")
head(coral_bleaching)
```

```{r warning=FALSE}
install.packages("tidyverse")
library(tidyverse)
library(dplyr)
library(ggplot2)
```

```{r}
# removing categories that do not apply to the topic i want to analysize with this dataset
coral_bleaching_clean <-  coral_bleaching %>%
  select(-"subregion", -"country", -"location", -"lat", -"lon", -"depth", -"water_temperature", -"country_code", -"source", -"water_temperature" , -"percentage_affected", -"coral_family", -"coral_species", -"mortality", -"mortality_code")
```


```{r}
coral_clean<- na.omit(coral_bleaching_clean)
```

```{r}
#clear all the unknowns and/or blank entries
coral_clean <- coral_clean %>%
  mutate(bleaching_severity = na_if(bleaching_severity, "Unknown"))

coral_clean2<- na.omit(coral_clean)
```

```{r}
# list the main categories in the clean dataset
distinct(coral_clean2, bleaching_severity)
```


```{r}
# Displays the number of observations per year. Not exactly what I want 
coral_clean2|>
  ggplot(aes(x=year, y=severity_code, color=region))+
  geom_point(data=coral_clean2, aes(x=year, y=severity_code, color=region), 
             position=position_jitter(width=0.5, height=0.2), alpha=0.6, size=2, inherit.aes=FALSE)+
  geom_point(position="dodge", size=2, pch=20)+

  facet_wrap(~region, scales= "fixed")+
  ggtitle("Centered Plot Title") +
  theme_minimal()+
  theme(
    strip.text = element_text(size=12, face="bold", hjust = 0.5),
    legend.position="bottom"
  )+
  labs(
    title="Coral Bleaching Severity by Region and Year",
    x="Year",
    y="Severity Code",
    color="Region")
    
```

```{r}
# experimenting with ways to display the data
#NO DON'T USE
coral_clean2|>
  ggplot(aes(x=year, y=severity_code, colour=region))+
  geom_violin(data=coral_clean2, aes(x=year, y=severity_code, fill=region), 
             position=position_jitter(width=0.5, height=0.2), alpha=0.6, size=2, inherit.aes=FALSE)+
  geom_point(position="dodge", size=1, pch=20)+

  facet_wrap(~region, scales= "fixed")+
  ggtitle("Centered Plot Title") +
  theme_minimal()+
  theme(
    strip.text = element_text(size=12, face="bold", hjust = 0.5),
    legend.position="bottom"
  )+
  labs(
    title="Coral Bleaching Severity by Region and Year",
    x="Year",
    y="Severity Code",
    color="Region")
```
```{r}
#NO DO NOT USE
coral_clean2|>
  ggplot(aes(x=year, y=severity_code, color=region))+
  geom_line(data=coral_clean2, aes(x=year, y=severity_code, color=region), 
             position=position_jitter(width=0.9, height=0.3), alpha=0.4, size=2, inherit.aes=FALSE)+
  geom_point(position="dodge", size=2, pch=20)+
  geom_line(linewidth = 1.0) +

  facet_wrap(~region, scales= "fixed")+
  ggtitle("Centered Plot Title") +
  theme_minimal()+
  theme(
    strip.text = element_text(size=12, face="bold", hjust = 0.6),
    legend.position="bottom"
  )+
  labs(
    title="Coral Bleaching Severity by Region and Year",
    x="Year",
    y="Severity Code",
    color="Region")
```
```{r}
#NO DO NOT USE
coral_clean2|>
  ggplot(aes(x=year, y=severity_code, fill = region)) +
geom_violin(alpha = 0.5) +
geom_jitter(position = position_jitter(width = 0.2), alpha = 0.6) +
theme_minimal() +


  facet_wrap(~region, scales= "fixed")+
  ggtitle("Centered Coral Bleaching Severity by Region and Year") +
  theme_minimal()+
  theme(
    strip.text = element_text(size=11, face="bold", hjust = 0.3),
    legend.position="bottom"
  )+
  labs(
    title="Coral Bleaching Severity by Region and Year",
    x="Year",
    y="Severity Code",
    color="Region")
```

```{r}
#NO DO NOT USE
ggplot(data = coral_clean2, aes(x=year, y=severity_code, fill = region)) +
  geom_boxplot()+

 facet_wrap(~region, scales= "fixed")+
  ggtitle("Centered Coral Bleaching Severity by Region and Year") +
  theme_minimal()+
  theme(
    strip.text = element_text(size=11, face="bold", hjust = 0.3),
    legend.position="bottom"
  )+
  labs(
    title="Coral Bleaching Severity by Region and Year",
    x="Year",
    y="Severity Code",
    color="Region")
```

```{r}
#listing the years in order to prepare to calculate the mean of the bleaching severity per region over time
year_order<-distinct(coral_clean2, year)
```

```{r}
average_severity_by_region <- coral_clean2 %>%
  group_by(region, year) %>%
  summarise(mean_severity = mean(severity_code, na.rm = TRUE))
```

```{r}
#final graph: this graph displays the mean bleaching severity across different regions of the world over time. The points represent the average severity for each year within each region. The facet wrap allows for a clear comparison of bleaching severity trends across different regions over time. The y-axis is labeled with descriptive categories for bleaching severity, making it easier to interpret the results.
average_severity_by_region|>
  ggplot(aes(x=year, y=mean_severity,  colour=region, size = mean_severity))+
  geom_point(data=average_severity_by_region, aes(x=year, y=mean_severity, colour=region), 
             position=position_jitter(width=0.5, height=0.2), alpha=0.7)+
  geom_point(position="dodge", size= 3.5, pch=20)+
  facet_wrap(~region)+

    scale_y_continuous(
    limits = c(0, 3),
    breaks = 0:3,
    labels = c("No Bleaching", "Low", "Medium", "High")
  ) +
  
  theme_minimal()+
  theme(
    strip.text = element_text(size=12, face="bold", hjust = 0.5),
    legend.position="bottom"
  )+
  labs(
    title="Coral Bleaching Severity by Region and Year",
    x="Year",
    y="Mean Bleaching Severity ",
    color="Regions")
```
```{r}
summary_table <- coral_clean2 %>%
  group_by(region, year) %>%
  summarise(
    mean_severity = mean(severity_code, na.rm = TRUE),
    n = n(),
    no_bleaching = sum(severity_code == 0),
    low = sum(severity_code == 1),
    medium = sum(severity_code == 2),
    high = sum(severity_code == 3),
    .groups = "drop"
  )

summary_table

```

```{r}
ggplot(summary_table,
       aes(x = year,
           y = mean_severity,
           colour = region,
           group = region)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  facet_wrap(~region) +
  scale_y_continuous(
    limits = c(0, 3),
    breaks = 0:3,
    labels = c("No Bleaching", "Low", "Medium", "High")
  ) +
  theme_bw() +
  labs(
    title = " Coral Bleaching Severity by Region and Year",
    x = "Year",
    y = " Bleaching Severity",
    colour = "Region"
  )
```

```{r}
#Reference code if needed
Coral_bleaching_clean|>
  ggplot(aes(x=year, y=percentage_affected, color=region))+
  geom_point(data=Coral_bleaching_clean, aes(x=year, y=mortality, color=region), 
             position=position_jitter(width=0.5, height=0.2), alpha=0.6, size=2, inherit.aes=FALSE)+
  geom_point(position="dodge", size=2, pch=21)+
  
  geom_errorbar(aes(ymin=mortality, ymax=mortality), width=0.5, position=position_dodge(0.9))+
  facet_wrap(~region, scales= "fixed")+
  theme_minimal()+
  theme(
    strip.text = element_text(size=12, face="bold"),
    legend.position="bottom"
  )+
  labs(
    title="Coral mortality by Region and Year",
    x="Year",
    y="Mortality",
    color="Region")
  )
```

```{r}
select_coral_bleaching|>
  ggplot(aes(x=year, y=severity_code, color=region))+
  geom_point(data=select_coral_bleaching, aes(x=year, y=bleaching_severity, color=region), 
             position=position_jitter(width=0.5, height=0.2), alpha=0.6, size=2, inherit.aes=FALSE)+
  geom_point(position="dodge", size=2, pch=21)+
  scale_y_discrete(limits = c("Low", "Medium", "High")) +
  
  geom_errorbar(aes(ymin=bleaching_severity, ymax=bleaching_severity), width=0.5, position=position_dodge(0.9))+
  facet_wrap(~region, scales= "fixed")+
  ggtitle("Centered Plot Title") +
  theme_minimal()+
  theme(
    strip.text = element_text(size=12, face="bold", hjust = 0.5),
    legend.position="bottom"
  )+
  labs(
    title="Coral Bleaching Severity by Region and Year",
    x="Year",
    y="Severity Code",
    color="Region")
```

```{r}

```








